### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by AlessiaBogoni** [VincenzoManto/Donations#2]
In game instructions need to correct: 
- number of matches available 
- new mouse and touch screen instructions

**Comment by VincenzoManto** [comment]
I'm going to close this issue cause:
- no jam available
- no instructions text provided

@AlessiaBogoni

**Comment by AlessiaBogoni** [comment]
more clear instruction: 
- point conversion 
- screenshot/video of the game UI (or just put the instruction on the side)
- clear statement of the number of round ans phase of the game
- clear "here you can see lives" and "here you can see match number"
- tell them they can share all lives except one because the rules is that everyone has to play two matches

**Comment by VincenzoManto** [comment]
Wrongly closed
