### ISSUE TITLE
# donated lives selection tool

### ISSUE THREAD

**Issue by AlessiaBogoni** [VincenzoManto/Donations#6]
Change the # donated lives selection tool. The slider that is available right now is difficult to use (especially when a small number of lives is available). 

 This would work with no issues for most of the participants and it's something very familiar 
![image](https://github.com/user-attachments/assets/194bdb6d-db84-481d-b0d2-1374787c884a)

Also clicking on the lives to select them could work, or somehow click on the last one you want to donate

**Comment by VincenzoManto** [comment]
Hmm... see if I can find something

**Comment by AlessiaBogoni** [comment]
<3 thanks

**Comment by AlessiaBogoni** [comment]
https://jam.dev/c/f0910665-a2d2-4da2-8ea9-2d25f4f8085b 
Good interface improvement but the + (and -) button cannot be clicked
