### ISSUE TITLE
Received lives are not added to availables

### ISSUE THREAD

**Issue by AlessiaBogoni** [VincenzoManto/Donations#8]
When you receive lives, they do not actually become available when playing

**Comment by VincenzoManto** [comment]
Tried 3 times and it works. This issue is not replicable @AlessiaBogoni

**Comment by AlessiaBogoni** [comment]
> Tried 3 times and it works. This issue is not replicable @AlessiaBogoni
@VincenzoManto 
https://jam.dev/c/f4fdab7d-add2-4cae-9c8c-6715807f79ae
